### PR TITLE
chore: tune GH Actions again

### PR DESCRIPTION
**Pull request by jasl**
Though we finally make the CI happy, I still see warnings, let's try more tuning

### CODE REVIEW

**Comment by kvinwang** [comment]
Not sure if we can mount a compression file system loop back image to save space. e.g. ZFS.

**Comment by kvinwang** [comment]
Interesting, I found the [ZFS repo's action](https://github.com/openzfs/zfs/runs/7440244265?check_suite_focus=true) aggressively cleans up the disk to have 66G available:
image

**Comment by jasl** [comment]
> Not sure if we can mount a compression file system loop back image to save space. e.g. ZFS.

I assume the warning is because cargo-cache, so I'm trying remove it to see what happens.

The space definitely enough for building khala, but the VM mount tmp folders into fixed .img which cause easily to make full, you can check details from https://github.com/easimon/maximize-build-space

**Comment by jasl** [comment]
> Interesting, I found the [ZFS repo's action](https://github.com/openzfs/zfs/runs/7440244265?check_suite_focus=true) aggressively cleans up the disk to have 66G available: image

For us

```
Filesystem                   Size  Used Avail Use% Mounted on
/dev/root                     84G   81G  2.3G  [9](https://github.com/Phala-Network/khala-parachain/runs/7447961290?check_suite_focus=true#step:8:10)8% /
devtmpfs                     3.4G     0  3.4G   0% /dev
tmpfs                        3.4G  4.0K  3.4G   1% /dev/shm
tmpfs                        695M  1.1M  694M   1% /run
tmpfs                        5.0M     0  5.0M   0% /run/lock
tmpfs                        3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/loop0                    62M   62M     0 [10](https://github.com/Phala-Network/khala-parachain/runs/7447961290?check_suite_focus=true#step:8:11)0% /snap/core20/1518
/dev/loop2                    47M   47M     0 100% /snap/snapd/16292
/dev/loop1                    68M   68M     0 100% /snap/lxd/22753
/dev/sda15                   105M  5.2M  100M   5% /boot/efi
/dev/sdb1                     14G   [12](https://github.com/Phala-Network/khala-parachain/runs/7447961290?check_suite_focus=true#step:8:13)G  1.1G  92% /mnt
tmpfs                        695M     0  695M   0% /run/user/1001
/dev/mapper/buildvg-buildlv   45G   27G   [18](https://github.com/Phala-Network/khala-parachain/runs/7447961290?check_suite_focus=true#step:8:19)G  60% /home/runner/work/khala-parachain/khala-parachain
```

**Comment by jasl** [comment]
Remove rust-cache will fix disk space warning.
However, the problem still

```
[Cargo test](https://github.com/Phala-Network/khala-parachain/runs/7450753073?check_suite_focus=true)
The hosted runner: GitHub Actions 2 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

**Comment by jasl** [comment]
Interesting...
I see on run tests step, it recompiles polkadot runtimes, I suspect this lead the VM crash.
I manually replay the CI steps in my local VM, the run cargo tests step doesn't compile anything which different behavior with GHA

**Comment by jasl** [comment]
image

IT IS MIRACLE !!!

**Pull request merged**
