### PR TITLE
Reduce release binary size.

### PR DESCRIPTION
**Pull request by Leechael**
The final binary size will reduce to around 55%.

### CODE REVIEW

**Comment by h4x3rotab** [comment]
We compile the production binary by `cargo build --profile production`, which enables lto. We didn't enable some optimization like lto because it takes 30-60 mins additional compilation time. What do you feel with the optimization enabled, in terms of the building time?

**Comment by Leechael** [comment]
> We compile the production binary by `cargo build --profile production`, which enables lto. We didn't enable some optimization like lto because it takes 30-60 mins additional compilation time. What do you feel with the optimization enabled, in terms of the building time?

This change intends to reduce the final binary size for the release build (which I think means distribution friendly). The most benefit comes from `strip = true` (typo here: `ltro` should be `lto`). The final binary size is 69MB, and the original size is 140MB.

Or if not necessary for release build, is the recommended way to do such optimization with `cargo build --config strip=true`?

**Comment by h4x3rotab** [comment]
We can tweak the build config as we want as long as it doesn't make the compilation process too long (like `--profile production`, which we only do for the production release)

**Comment by jasl** [comment]
`strip = true` means remove symbols which will make debugging harder,
I'm not an expert for this, maybe @kvinwang could help to figure it value

**Comment by jasl** [comment]
and I'm not sure `opt-level = "z"` is covered by `opt-level = "3"`, performance is the first priority

**Pull request closed without merging**
