### PR TITLE
Enable fat contract on Thala

### PR DESCRIPTION
**Pull request by jasl**

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Is `phala-trie-storage` not used?

**Comment by jasl** [comment]
> Is `phala-trie-storage` not used?

`phala-types` declares `phala-trie-storage`

`phala-trie-storage = { path = "../../crates/phala-trie-storage", default-features = false, optional = true }`

though it's optional, but `Cargo` still trying to fetch it, so if the crate not there, the dependency check will failed.

**Comment by h4x3rotab** [comment]
OK. Then easier to just keep it as is. Another option is to remove it completely, but that makes syncing harder

**Comment by jasl** [comment]
> OK. Then easier to just keep it as is. Another option is to remove it completely, but that makes syncing harder

Yep, this is the simplest way to made Cargo happy

**Pull request merged**
